ERP/Controllers/BillController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FreeERP.Model;

namespace FreeERP.Controllers
{
    public class BillController : Controller
    {
        [HttpPost]
        [Route("/bill")]
        public IActionResult CreateBill(
            [FromForm(Name = "UserID")] string userId,
            [FromForm(Name = "Content")] string content,
            [FromForm(Name = "Amount")] int amount)
        {
            Bill bill = new(userId, content, amount);
            bill.SaveToDB();
            return View();
        }

        [HttpGet]
        [Route("/bill/{bill_id}")]
        public IActionResult BillDetail([FromRoute(Name = "bill_id")] string billId) {
            return View(BillFactory.QueryBillById(billId));
        }

        [HttpGet]
        [Route("/bill/qr/{bill_id}")]
        public IActionResult BillQR([FromRoute(Name = "bill_id")] string billId) {
            return View((object)billId);
        }

        [HttpPost]
        [Route("/bill/checkout/{bill_id}")]
        public IActionResult BillCheckout([FromRoute(Name = "bill_id")] string billId)
        {
            string error = BillFactory.Pay(billId);
            if (error != "")
            {
                return BadRequest(error);
            }
            return Ok("Successfully");
        }
    }
}

ERP/Views/Bill/BillDetail.cshtml
@model Bill

<div class="container mx-auto max-w-sm bg-white shadow-lg rounded-lg overflow-hidden my-8">
    <div class="px-6 py-4">
        <h1 class="text-2xl font-bold mb-4">Bill Detail:</h1>
        <p class="mb-2"><b>Bill Content:</b> @Model.Content</p>
        <p class="mb-4"><b>Bill Amount:</b> @Model.Amount<span class="font-semibold">$</span></p>
        @using (Html.BeginForm("BillQR", "Bill", new { bill_id = Model.ID }, FormMethod.Get))
        {
            <button type="submit" class="w-full bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">
                Checkout
            </button>
        }
    </div>
</div>

ERP/Views/Bill/BillQR.cshtml
@model string

<div class="container mx-auto p-8">
    <img src="~/qr.png" class="w-32 h-32 mx-auto mb-4 rounded-md shadow-md" />

    <button onclick="checkout()" class="block mx-auto bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded w-32">
        <i class="fas fa-sync mr-2"></i> OK
    </button>

    <div id="update_result" class="mt-4 text-center text-gray-700 italic"></div>
</div>

<script>
    function checkout() {
        var billId = '@Model';

        fetch('/bill/checkout/' + billId, {
            method: 'POST'
        })
            .then(response => response.text())
            .then(data => {
                document.getElementById("update_result").innerHTML = data;
            })
            .catch(error => {
                document.getElementById("update_result").innerHTML = error;
            });
    }
</script>

ERP/Views/Bill/CreateBill.cshtml
<body class="bg-gray-100">
    <div class="container mx-auto px-4 py-8">
        <h1 class="text-4xl font-bold text-center text-blue-500 mb-6">
            Create Bill successfully
        </h1>
    </div>
</body>